/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Affinity */

#ifndef _Included_Affinity
#define _Included_Affinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Affinity
 * Method:    setAffinityN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Affinity_setAffinityN
  (JNIEnv *, jclass, jint);

/*
 * Class:     Affinity
 * Method:    checkAffinityN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Affinity_checkAffinityN
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
