/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Forker */

#ifndef _Included_Forker
#define _Included_Forker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Forker
 * Method:    doFork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Forker_doFork
  (JNIEnv *, jobject);

/*
 * Class:     Forker
 * Method:    doExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Forker_doExit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
