/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_columbia_cs_psl_metamorphic_util_Forker */

#ifndef _Included_edu_columbia_cs_psl_metamorphic_util_Forker
#define _Included_edu_columbia_cs_psl_metamorphic_util_Forker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_columbia_cs_psl_metamorphic_util_Forker
 * Method:    doFork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_columbia_cs_psl_metamorphic_util_Forker_doFork
  (JNIEnv *, jclass);

/*
 * Class:     edu_columbia_cs_psl_metamorphic_util_Forker
 * Method:    doExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_columbia_cs_psl_metamorphic_util_Forker_doExit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
