/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pipe */

#ifndef _Included_Pipe
#define _Included_Pipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pipe
 * Method:    createPipe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Pipe_createPipe
  (JNIEnv *, jobject);

/*
 * Class:     Pipe
 * Method:    writePipe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Pipe_writePipe
(JNIEnv *, jobject, jlong);

/*
 * Class:     Pipe
 * Method:    readPipe
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_Pipe_readPipe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
